version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    volumes:
      - ./data:/app/data
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
